DEPENDENCY_QUESTIONS = [
  "Is changing the evidence of {node1} going to change the probability of {node2}?",
  "Is {node1} d-connected to {node2}?",
  "Is {node1} d-separated from {node2}?",
  "Is {node1} dependent on {node2}?",
  "Is {node1} independent of {node2}?",
  "Does a path exist from {fromNode} to {toNode}?",
  "Can information flow from {fromNode} to {toNode}?",
  "Are {fromNode} and {toNode} dependent?",
  "Is there any direct or indirect connection between {fromNode} and {toNode}?",
  "Can {fromNode} influence {toNode}?",
  "Is {toNode} reachable from {fromNode}?",
  "Is {toNode} conditionally dependent on {fromNode}?",
  "Does changing {node1} affect the probability of {node2}?",
  "If {node1} changes, will {node2}’s belief be affected?",
  "Can a change in {node1} propagate to {node2}?",
  "Would observing {node1} provide any information about {node2}?",
  "Do {node1} and {node2} have a dependency path between them?",
  "Are {node1} and {node2} connected in the Bayesian network?",
  "Does any active path exist between {node1} and {node2}?",
  "Can knowledge of {node1} update our belief about {node2}?",
  "Is there any active connection between {node1} and {node2}?",
  "Does {node1} influence {node2}, directly or indirectly?",
  "If {node1} is observed, does it affect {node2}?",
  "Would {node2}’s probability change if {node1} were observed?",
  "Is {node1} conditionally dependent on {node2} given the current evidence?",
  "Can {node1} and {node2} be considered independent given no evidence?",
  "Is there a probabilistic link between {node1} and {node2}?",
  "Does {node1} transmit any information to {node2}?",
  "If no evidence is observed, are {node1} and {node2} connected?",
  "Does a dependency path exist from {fromNode} to {toNode}?",
  "Can the effect of {fromNode} reach {toNode} through any path?",
  "Does the network structure allow influence from {fromNode} to {toNode}?",
  "Would observing {fromNode} tell us anything about {toNode}?",
  "Are {fromNode} and {toNode} linked through an unblocked path?",
  "Does {fromNode} have a causal effect on {toNode}?",
  "Is there any indirect dependency between {fromNode} and {toNode}?",
  "Does {fromNode} share any ancestor or descendant with {toNode}?",
  "Would {toNode}’s probability shift if {fromNode} were known?",
  "Are {fromNode} and {toNode} connected through a collider or chain structure?",
  "Is {toNode} reachable via a directed or undirected path from {fromNode}?",
  "Does an unblocked trail exist between {fromNode} and {toNode}?",
  "Are {node1} and {node2} correlated in the network?",
  "Is there statistical dependence between {node1} and {node2}?",
  "Would knowing {node1} reduce uncertainty about {node2}?",
  "Can evidence from {fromNode} propagate to {toNode}?",
  "Does any open trail connect {fromNode} and {toNode}?",
  "Is there an unblocked chain of nodes between {fromNode} and {toNode}?",
  "Can a change in {fromNode} indirectly influence {toNode} through intermediate nodes?",
  "If we intervene on {fromNode}, would that affect {toNode}?",
  "Does {fromNode} and {toNode} belong to the same dependency cluster?",
  "Are {node1} and {node2} still dependent after conditioning on known evidence?",
  "Can {node1} affect {node2}’s posterior distribution?",
  "Would a change in {node1}’s evidence propagate to {node2}?",
  "Is {node1} part of the dependency structure that determines {node2}?",
  "Can {node1} influence the belief propagation to {node2}?",
  "Is there any non-blocked route between {node1} and {node2}?"
]

COMMON_CAUSE_QUESTIONS = [
  "What is the common cause of {node1} and {node2}?",
  "Is there a common cause that influences both {node1} and {node2}?",
  "Which variable acts as a common parent/grandparent of {node1} and {node2}?",
  "Do {node1} and {node2} share the same parent/grandparent node?",
  "List all possible common causes between {node1} and {node2}.",
  "Which node connects both {node1} and {node2} as a common ancestor?",
  "What is the minimal set of nodes that explain the common cause relationship between {node1} and {node2}?",
  "In the network, does any latent variable act as a hidden common cause for {node1} and {node2}?",
  "Is there a node that causes changes in both {node1} and {node2}?",
  "What variable could be responsible for influencing both {node1} and {node2}?",
  "Which parent/grandparent node explains why {node1} and {node2} are correlated?",
  "Who is the 'root cause' that affects both {node1} and {node2}?",
  "Do {node1} and {node2} have a common upstream cause?",
  "Is there a higher-level node that explains both {node1} and {node2}?",
  "What ancestor variable links {node1} and {node2} together?",
  "Is there any hidden or unobserved variable causing both {node1} and {node2}?",
  "Which node in the network is the main source of influence for both {node1} and {node2}?",
  "Could {node1} and {node2} be correlated because of the same cause?",
  "Which upstream factor explains the relationship between {node1} and {node2}?"
  "Is there any shared parent/grandparent that explains both {node1} and {node2}?",
  "Could both {node1} and {node2} be descendants of the same parent/grandparent?",
  "Is there a direct or indirect parent/grandparent node common to both {node1} and {node2}?",
  "Can the correlation between {node1} and {node2} be traced back to a common ancestor?",
  "What common factor leads to both {node1} and {node2} changing together?",
  "Which node would you identify as the shared influencer of {node1} and {node2}?",
  "Is the connection between {node1} and {node2} due to a shared parent/grandparent variable?",
  "Are {node1} and {node2} connected because of a mutual causal ancestor?",
  "Does a single upstream variable influence both {node1} and {node2}?",
  "What variable lies upstream of both {node1} and {node2}?",
  "Which higher-level node best explains their correlation?",
  "Is there a node that simultaneously affects both {node1} and {node2}?",
  "Which shared cause could explain the observed dependency between {node1} and {node2}?",
  "Are both {node1} and {node2} affected by a single hidden node?",
  "Which ancestor variable has pathways leading to both {node1} and {node2}?",
  "Does the structure suggest a shared parent node for {node1} and {node2}?",
  "If {node1} and {node2} are dependent, what is the likely common cause?",
  "Could both {node1} and {node2} be outcomes of the same latent variable?",
  "What parent node/grandparent node best accounts for the correlation between {node1} and {node2}?",
  "Is there an unobserved node that jointly causes both {node1} and {node2}?",
  "What underlying cause might explain both {node1} and {node2}’s outcomes?"
]

COMMON_EFFECT_QUESTIONS = [
  "What is the common effect of {node1} and {node2}?",
  "Is there a common effect that influences both {node1} and {node2}?",
  "Which variable acts as a common child/grandchild of {node1} and {node2}?",
  "Do {node1} and {node2} share the same child/grandchild node?",
  "List all possible common effects between {node1} and {node2}.",
  "Which node connects both {node1} and {node2} as a common descendant?",
  "What is the minimal set of nodes that explain the common effect relationship between {node1} and {node2}?",
  "Which node is influenced by both {node1} and {node2}?",
  "Is there any variable that results from both {node1} and {node2}?",
  "Which child/grandchild node is affected by both {node1} and {node2}?",
  "Do {node1} and {node2} lead to the same outcome node?",
  "What node depends on both {node1} and {node2}?",
  "Could {node1} and {node2} both contribute to the same effect?",
  "What is the shared consequence of {node1} and {node2}?",
  "Is there a node that combines the influence of {node1} and {node2}?",
  "Does any variable act as a collider between {node1} and {node2}?",
  "Which descendant node captures the joint influence of {node1} and {node2}?",
  "Which variable serves as a merging point for {node1} and {node2}’s paths?",
  "What shared output arises due to both {node1} and {node2}?",
  "Is there a child/grandchild node that both {node1} and {node2} directly or indirectly affect?",
  "Which variable is the result of both {node1} and {node2}?",
  "Do {node1} and {node2} share a common outcome?",
  "What variable receives influence from both {node1} and {node2}?",
  "Is there a node that both {node1} and {node2} point to?",
  "What is the downstream effect of both {node1} and {node2}?",
  "Which node acts as a child of both {node1} and {node2}?",
  "Does any descendant depend on both {node1} and {node2}?",
  "Can {node1} and {node2} lead to the same consequence in the model?",
  "Which variable acts as the collider that both {node1} and {node2} feed into?",
  "Is there a joint effect node caused by {node1} and {node2}?",
  "Which descendant combines the influence of {node1} and {node2}?",
  "What node is determined by the interaction of {node1} and {node2}?",
  "What shared variable captures the joint effect of {node1} and {node2}?",
  "Could {node1} and {node2} influence the same observation node?",
  "Is there a node that receives input from both {node1} and {node2}?",
  "Which common descendant is affected by both {node1} and {node2}?",
  "What variable aggregates the outcomes of {node1} and {node2}?",
  "Is there a variable downstream of both {node1} and {node2}?",
  "Which outcome variable reflects the effects of both {node1} and {node2}?",
  "Which node sits at the intersection of both {node1} and {node2}’s causal paths?",
]

BLOCKED_EVIDENCES_QUESTIONS = [
  "What is the minimal set of nodes that would block the dependency between {node1} and {node2}?",
  "Which node acts as a blocker for the dependency between {node1} and {node2}?",
  "Is there a node that, when observed, would block the dependency between {node1} and {node2}?",
  "List all possible nodes that would block the dependency between {node1} and {node2}.",
  "What set of evidences would block the path between {node1} and {node2}?",
  "What is the minimal set of nodes that explain the blocked dependency relationship between {node1} and {node2}?",
  "Which evidence node would make {node1} and {node2} independent?",
  "If we observe a certain node, which one would block the path between {node1} and {node2}?",
  "What node should we condition on to d-separate {node1} and {node2}?",
  "Which observation would cut off the information flow between {node1} and {node2}?",
  "Identify the variable that d-separates {node1} from {node2}.",
  "Which conditioning set would stop {node1} from affecting {node2}?",
  "What is the smallest evidence set that would block all active paths between {node1} and {node2}?",
  "Is there any node that, once known, breaks the dependency between {node1} and {node2}?",
  "Which node lies on the path between {node1} and {node2} and can act as a blocking point?",
  "If we want {node1} and {node2} to be independent, which nodes should we observe?",
  "What combination of variables can act as a separator between {node1} and {node2}?",
  "Which nodes should be set as evidence to deactivate the connection between {node1} and {node2}?",
  "Can you identify a conditioning variable that blocks the information transfer between {node1} and {node2}?",
  "Which minimal set of evidences would achieve d-separation for {node1} and {node2}?",
  "When conditioning, what nodes would close all open paths between {node1} and {node2}?",
  "Which nodes act as evidence that can block the dependency path between {node1} and {node2}?",
  "What evidence would you add to make {node1} and {node2} independent?",
  "Which variable do we need to condition on to block the influence of {node1} on {node2}?",
  "Is there a single node that, if observed, would d-separate {node1} and {node2}?",
  "What node do we observe to stop information flow between {node1} and {node2}?",
  "If we want to remove dependency between {node1} and {node2}, which node should be observed?",
  "Which conditioning variable would neutralize the connection between {node1} and {node2}?",
  "What evidence can make the two nodes {node1} and {node2} conditionally independent?",
  "What evidence variable breaks the link between {node1} and {node2}?",
  "If {node1} and {node2} are dependent, what evidence can block their connection?",
  # "Which minimal set of evidence variables will ensure d-separation of {node1} and {node2}?",
  "Which observation effectively closes all open trails between {node1} and {node2}?",
  "Is there any node you could observe to stop {node1} from influencing {node2}?",
  "What conditioning set should be applied to make {node1} and {node2} independent?",
  "If we observe {evidence}, would that block the path between {node1} and {node2}?",
  "Which node, if conditioned on, will eliminate the dependency between {node1} and {node2}?",
  "What evidence nodes would you select to close all active connections between {node1} and {node2}?",
  "Can you find a separator that blocks any information from flowing between {node1} and {node2}?",
  "Which variable, if known, would disconnect {node1} and {node2} in the network?",
  "What minimal evidence set is sufficient to stop any influence between {node1} and {node2}?",
  "Which observed variable will cut all active paths linking {node1} and {node2}?",
  "What evidence nodes would ensure that {node1} and {node2} become independent?",
  "Which variables can act as d-separators for {node1} and {node2}?",
  "What observations would you add to close all dependency routes between {node1} and {node2}?",
  "If you want to block the flow of belief from {node1} to {node2}, which nodes should be conditioned on?",
  "What set of evidence variables can fully deactivate all open paths between {node1} and {node2}?"
]

EVIDENCE_CHANGE_RELATIONSHIP_QUESTIONS = [
  "Is the relationship between {node1} and {node2} affected by the evidence of {evidence}?",
  "Does observing {evidence} change the dependency between {node1} and {node2}?",
  "Can information flow from {node1} to {node2} through knowing {evidence}?",
  "Is there a path that links {node1} to {node2} through knowing {evidence}?",
  "Is {toNode} reachable from {fromNode} through knowing {evidence}?",
  "Does setting {evidence} as evidence change the connection between {node1} and {node2}?",
  "After observing {evidence}, do {node1} and {node2} still influence each other?",
  "Does conditioning on {evidence} block or open the path between {node1} and {node2}?",
  "If {evidence} is known, does it make {node1} and {node2} independent?",
  "Is the dependency between {node1} and {node2} broken when {evidence} is observed?",
  "Would observing {evidence} activate or deactivate the connection between {node1} and {node2}?",
  "If we condition on {evidence}, can {node1} still affect {node2}?",
  "How does {evidence} influence the relationship between {node1} and {node2}?",
  "Is the path between {node1} and {node2} open or closed once we observe {evidence}?",
  "Would {node1} and {node2} become independent if {evidence} were observed?",
  "Is the link between {node1} and {node2} opened or closed when {evidence} is known?",
  "Would learning about {evidence} change how {node1} and {node2} relate to each other?",
  "Does evidence on {evidence} affect the flow of influence between {node1} and {node2}?",
  "Would conditioning on {evidence} make {node1} explain {node2} better or not at all?",
  "If we know {evidence}, is there still any active path between {node1} and {node2}?",
  "Can {node1} send information to {node2} after conditioning on {evidence}?",
  "Does adding {evidence} as known information alter the d-connection between {node1} and {node2}?",
  "Is {node1} still reachable from {node2} when {evidence} is part of the conditioning set?",
  "If we observe {evidence}, does it make {node1} and {node2} dependent or independent?",
  "Would the presence of evidence on {evidence} alter the probabilistic relationship between {node1} and {node2}?",
  "After observing {evidence}, do we expect {node1} and {node2} to remain connected in the BN?",
  "If {evidence} becomes known, does it create or destroy the dependency path between {node1} and {node2}?",
  "Could knowing {evidence} make an indirect path appear between {node1} and {node2}?",
  "Does {evidence} activate any previously blocked path between {node1} and {node2}?",
  "After we condition on {evidence}, is there still a route for information between {node1} and {node2}?"
]

PROBABILITY_QUESTIONS = [
  "What is the probability of {node} given {evidence}?",
  "Given {evidence}, what is the probability of {node}?",
  "Knowing {evidence}, what is the probability of {node}?",
  "If I know {evidence}, what is the probability of {node}?",
  "What is P({node} | {evidence})?",
  "Can you compute the probability of {node} given {evidence}?",
  "How likely is {node} when {evidence} is observed?",
  "What’s the likelihood of {node} under {evidence}?",
  "If {evidence} holds true, what is the chance of {node}?",
  "What is the conditional probability of {node} when {evidence} is true?",
  "What is the posterior probability of {node} after observing {evidence}?",
  "How does observing {evidence} change the probability of {node}?",
  "After conditioning on {evidence}, what is P({node})?",
  "What value does the belief in {node} take once {evidence} is known?",
  "If we observe {evidence}, what’s the updated probability of {node}?",
  "Given that {evidence} occurred, what’s the chance that {node} will occur?",
  "Based on {evidence}, what do we believe about {node}?",
  "Given {evidence}, what are the probabilities of all states of {node}?",
  "What is the belief value of {node} conditioned on {evidence}?",
  "How much does {evidence} increase or decrease the probability of {node}?",
  "Given {evidence}, what’s the expected likelihood of {node}?",
  "If {evidence} were known, what would be P({node})?",
  "What is the probability of {node} conditional on {evidence} being observed?",
  "How does {evidence} affect the belief in {node}?",
  "Given we have observed {evidence}, what’s the belief in {node}?",
  "What is the computed probability distribution for {node} given {evidence}?",
  "If {evidence} is observed, what is the updated likelihood of {node}?",
  "Can you tell me the probability of {node} after seeing {evidence}?",
  "Given {evidence}, what’s the most likely value of {node}?",
  "After observing {evidence}, what’s the posterior of {node}?",
  "Can you calculate P({node} | {evidence})?",
  "How certain are we about {node} after seeing {evidence}?",
  "Under {evidence}, what’s the chance of {node} happening?",
  "If {evidence} occurs, how does that affect the likelihood of {node}?",
  "Given {evidence}, what percentage chance is assigned to {node}?",
]

HIGHEST_IMPACT_EVIDENCE_QUESTIONS = [
  "What is the highest impact evidence on {node}?",
  "Which evidence has the most impact on {node}?",
  "What is the evidence that has the highest impact on {node}?",
  "Which evidence is the most influential on {node}?",
  "What evidence has the biggest effect on {node}?",
  "Which evidence is the most important for {node}?",
  "What evidence has the biggest impact on {node}?",
  "Which observed variable affects {node} the most?",
  "What piece of evidence changes {node}’s belief the most?",
  "Which variable has the strongest influence on {node}?",
  "Which evidence causes the largest shift in {node}’s probability distribution?",
  "Which input variable makes the biggest difference to {node}?",
  "Which evidence plays the key role in explaining {node}?",
  "What is the strongest driver of change in {node}?",
  "If you had to choose one piece of evidence, which impacts {node} the most?",
  "What variable, when observed, changes {node}’s probability the most?",
  "Which evidence variable provides the most information about {node}?",
  "What is the single most influential observation for {node}?",
  "Among all evidences, which one has the greatest impact on {node}?",
  "Which finding causes the biggest belief shift in {node}?",
  "What is the top contributing evidence for {node}?",
  "Which piece of evidence has the most significant effect on {node}?",
  "Which evidence has the greatest overall influence on {node}’s posterior belief?",
  "What is the main evidence driving the probability changes in {node}?",
  "Which evidence variable shifts {node}’s probability the furthest?",
  "What observation provides the strongest signal for {node}?",
  "Which evidence, when added, changes {node}’s beliefs the most?",
  "What is the key evidence node that most affects {node}?",
  "Which single evidence has the dominant effect on {node}?",
  "Which observed node makes {node}’s belief change most dramatically?"
]